# Generated by Django 5.0.6 on 2024-06-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='Rol',
        ),
    ]
