# Generated by Django 5.0.6 on 2024-06-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_rol_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso',
            table='permiso',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='rolpermiso',
            table='rolpermiso',
        ),
    ]
