# Generated by Django 5.0.6 on 2024-06-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
