# Generated by Django 5.0.6 on 2024-06-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_correo_electronico'),
        ('habitaciones', '0002_alter_habitacion_table_alter_tipohabitacion_table'),
        ('reservas', '0002_alter_reserva_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Estado de la Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateField(verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion', verbose_name='Habitación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_huespedes',
            field=models.IntegerField(verbose_name='Total Huéspedes'),
        ),
    ]
