# Generated by Django 5.0.6 on 2024-06-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='habitacion',
            table='habitacion',
        ),
        migrations.AlterModelTable(
            name='tipohabitacion',
            table='tipo_habitacion',
        ),
    ]
