# Generated by Django 5.0.6 on 2024-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionEspecifica',
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='clave',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='valor',
            field=models.CharField(max_length=255, verbose_name='Valor'),
        ),
    ]
