# Generated by Django 5.0.6 on 2024-06-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_delete_configuracionespecifica_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuraciongeneral',
            table='configsys',
        ),
    ]
